### ISSUE TITLE
Currently does not compile

### ISSUE THREAD

**Issue by hmeine** [IDEDARY/stardawn#1]
I was interested in this example which was linked to from the lunex README, because I wanted to know what lunex is and what it does.  However, the example does not compile currently.

First, I found this in Cargo.toml:
```
#bevy_lunex = "0.0.3"
bevy_lunex = { path = "/home/dominik/Projects/Bytestring/bevy-lunex" }
```
Needless to say that `/home/dominik/Projects/Bytestring/bevy-lunex` does not exist on my machine. :-)

I tried compiling the example against bevy_lunex 0.0.6, which seems to be the latest release, and I assumed that the fact that a local checkout was used above meant that 0.0.3 was too old.  In the meantime, I found that neither of these versions worked, nor did 0.0.5.

**Comment by IDEDARY** [comment]
Stardawn example used direct github branch of Bevy Lunex, which was located on that path on my machine. There should have been a commented out version with github path next to it. If not, then thats my fault, I might have deleted it or it got lost in the version control. Anyways, I have moved my focus onto pushing the lib to crates.io with examples directly in the examples folder on the main branch + some bugfixes and improvements. I havent had time to check if this compiles, but I will fix it soon with non changing version of bevy lunex on crates.io (i used this repo to dogfeed lunex)

**Comment by IDEDARY** [comment]
Yeah I fixed the issue. There was some unfinished work in progress that I abandoned midway and didn't come back yet (had to focus on different issues). Spearheading UI framework solo is hard.

**Comment by DaRAGingLunatic** [comment]
I was having a look at the code due to seeing this LunexUI on the Reddit Bevy channel. I went to investigate. Tried getting it to run, the CyberPunk one, Had an issue. Tried getting this one to run, Have an issue. 

error: linking with `link.exe` failed: exit code: 1189  
  = note: LINK : fatal error LNK1189: library limit of 65535 objects exceeded

error: could not compile `bevy_dylib` (lib) due to previous error . Anyways It all looks great. Keep it up! I mean the code looks great. Art too. But the code looks a lot nicer than Bevy's UI code.

**Comment by IDEDARY** [comment]
> I was having a look at the code due to seeing this LunexUI on the Reddit Bevy channel. I went to investigate. Tried getting it to run, the CyberPunk one, Had an issue. Tried getting this one to run, Have an issue.
> 
> error: linking with `link.exe` failed: exit code: 1189 = note: LINK : fatal error LNK1189: library limit of 65535 objects exceeded
> 
> error: could not compile `bevy_dylib` (lib) due to previous error . Anyways It all looks great. Keep it up! I mean the code looks great. Art too. But the code looks a lot nicer than Bevy's UI code.

Hi, thanks for feedback. It seems like you are using windows. This issue is not related to this project, but to bevy (rust) itself. There is an issue for it [here](https://github.com/rust-lang/rust/issues/53014) on rust lang repo. For you to compile, please remove the "dynamic_linking" tag from the cargo file. That feature is used to make the compilation several times faster, so unfortunately, you windows folk will have to bear with slower compile times :/
